# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170109_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 16, 15, 53, 725254, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 16, 15, 53, 725282, tzinfo=utc)),
        ),
    ]
